[master]
51.12.80.201 ansible_user=azureuser ansible_ssh_private_key_file=../terraform/id_rsa_devops ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[worker]
4.223.64.5 ansible_user=azureuser ansible_ssh_private_key_file=../terraform/id_rsa_devops ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k3s_cluster:children]
master
worker
